### ISSUE TITLE
can i use this in my worker

### ISSUE THREAD

**Issue by warrn** [EverlastingBugstopper/cargo-fast#1]
hi long time listener first time caller

how do i leverage this library for my innovative new cloudflare :tm: worker, making it go fast

ty

**Comment by EverlastingBugstopper** [comment]
hi @warrn 

so glad to have you in on the show!

i have to say your question made me think for a while. looks like workers not only support rust, but have it listed as the third of many supported languages in their docs! 

[yw](https://developers.cloudflare.com/workers/platform/languages)
